local flowerInfo = require("scripts.flowerInfo")
local mouseCheck = require("scripts.mouseCheck")
local inScreen = false
local screenSelection = 1
local selected = 1
local page = 1
local flipcd = false

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("/flower_factory#flowery", "flowerselect", {uwu = 1})
end

local function loadPage(p)
	gui.set_scale(gui.get_node("page1"), vmath.vector3(2/30, 2/30, 1))
	gui.set_position(gui.get_node("page1"), vmath.vector3(-8.5, 0, 0))
	gui.set_scale(gui.get_node("page2"), vmath.vector3(2/30, 2/30, 1))
	gui.set_position(gui.get_node("page2"), vmath.vector3(8.5, 0, 0))
	if selected == page then
		gui.play_flipbook(gui.get_node("useButton"), "clicked")
	end
	if p > 0 then
		local flower = flowerInfo.ID(p)
		gui.set_text(gui.get_node("description"), flower[3])
		if flower[4] then
			gui.set_visible(gui.get_node("photo1"), true)
			gui.set_visible(gui.get_node("photo2"), true)
			gui.set_visible(gui.get_node("flower"), true)
			gui.play_flipbook(gui.get_node("flower"), "1", nil, {playback_rate = 0})
			gui.set_flipbook_cursor(gui.get_node("flower"), (4 * p - 1) / 127)
			gui.set_text(gui.get_node("titleText"), flower[1])
			gui.set_text(gui.get_node("subtitleText"), flower[2])
		else
			gui.set_text(gui.get_node("titleText"), "Undiscovered")
			gui.set_text(gui.get_node("subtitleText"), "?????")
			gui.set_visible(gui.get_node("photo1"), false)
			gui.set_visible(gui.get_node("photo2"), false)
			gui.set_visible(gui.get_node("flower"), false)
		end
	end
end

local function left(p)
	local flower = flowerInfo.ID(p + 1)
	gui.set_text(gui.get_node("description1"), flower[3])
	if flower[4] then
		gui.set_text(gui.get_node("titleText1"), flower[1])
		gui.set_text(gui.get_node("subtitleText1"), flower[2])
	else
		gui.set_text(gui.get_node("titleText1"), "Undiscovered")
		gui.set_text(gui.get_node("subtitleText1"), "?????")
	end
	flower = flowerInfo.ID(p)
	if flower[4] then
		gui.set_visible(gui.get_node("photo3"), true)
		gui.set_visible(gui.get_node("photo4"), true)
		gui.set_visible(gui.get_node("flower1"), true)
		gui.play_flipbook(gui.get_node("flower1"), "1", nil, {playback_rate = 0})
		gui.set_flipbook_cursor(gui.get_node("flower1"), (4 * (p) - 1) / 127)
	else
		gui.set_visible(gui.get_node("photo3"), false)
		gui.set_visible(gui.get_node("photo4"), false)
		gui.set_visible(gui.get_node("flower1"), false)
	end
	gui.set_scale(gui.get_node("page2"), vmath.vector3(0, 2/30, 1))
	gui.set_position(gui.get_node("page2"), vmath.vector3(0, 0, 0))
	flower = flowerInfo.ID(p)
	gui.set_text(gui.get_node("description"), flower[3])
	if flower[4] then
		gui.set_text(gui.get_node("titleText"), flower[1])
		gui.set_text(gui.get_node("subtitleText"), flower[2])
	else
		gui.set_text(gui.get_node("titleText"), "Undiscovered")
		gui.set_text(gui.get_node("subtitleText"), "?????")
	end
	gui.animate(gui.get_node("page1"), gui.PROP_SCALE, vmath.vector3(0, 2/30, 1), gui.EASING_INSINE, .5, 0, function()
		gui.animate(gui.get_node("page2"), gui.PROP_SCALE, vmath.vector3(2/30, 2/30, 1), gui.EASING_OUTSINE, .5, 0)
	end)
	gui.animate(gui.get_node("page1"), gui.PROP_POSITION, vmath.vector3(0, 0, 0), gui.EASING_INSINE, .5, 0, function()
		gui.animate(gui.get_node("page2"), gui.PROP_POSITION, vmath.vector3(8.5, 0, 0), gui.EASING_OUTSINE, .5, 0, function()
			loadPage(p)
			flipcd = false
		end)
	end)
end

local function right(p)
	local flower = flowerInfo.ID(p)
	gui.set_text(gui.get_node("description1"), flower[3])
	if flower[4] then
		gui.set_text(gui.get_node("titleText1"), flower[1])
		gui.set_text(gui.get_node("subtitleText1"), flower[2])
	else
		gui.set_text(gui.get_node("titleText1"), "Undiscovered")
		gui.set_text(gui.get_node("subtitleText1"), "?????")
	end
	flower = flowerInfo.ID(p - 1)
	gui.set_scale(gui.get_node("page1"), vmath.vector3(0, 2/30, 1))
	gui.set_position(gui.get_node("page1"), vmath.vector3(0, 0, 0))
	if flower[4] then
		gui.set_visible(gui.get_node("photo3"), true)
		gui.set_visible(gui.get_node("photo4"), true)
		gui.set_visible(gui.get_node("flower1"), true)
		gui.play_flipbook(gui.get_node("flower1"), "1", nil, {playback_rate = 0})
		gui.set_flipbook_cursor(gui.get_node("flower1"), (4 * (p - 1) - 1) / 127)
	else
		gui.set_visible(gui.get_node("photo3"), false)
		gui.set_visible(gui.get_node("photo4"), false)
		gui.set_visible(gui.get_node("flower1"), false)
	end
	flower = flowerInfo.ID(p)
	if flower[4] then
		gui.set_visible(gui.get_node("photo2"), true)
		gui.set_visible(gui.get_node("photo1"), true)
		gui.set_visible(gui.get_node("flower"), true)
		gui.play_flipbook(gui.get_node("flower"), "1", nil, {playback_rate = 0})
		gui.set_flipbook_cursor(gui.get_node("flower"), (4 * p - 1) / 127)
	else
		gui.set_visible(gui.get_node("photo1"), false)
		gui.set_visible(gui.get_node("photo2"), false)
		gui.set_visible(gui.get_node("flower"), false)
	end
	gui.animate(gui.get_node("page2"), gui.PROP_SCALE, vmath.vector3(0, 2/30, 1), gui.EASING_INSINE, .5, 0, function()
		gui.animate(gui.get_node("page1"), gui.PROP_SCALE, vmath.vector3(2/30, 2/30, 1), gui.EASING_OUTSINE, .5, 0)
	end)
	gui.animate(gui.get_node("page2"), gui.PROP_POSITION, vmath.vector3(0, 0, 0), gui.EASING_INSINE, .5, 0, function()
		gui.animate(gui.get_node("page1"), gui.PROP_POSITION, vmath.vector3(-8.5, 0, 0), gui.EASING_OUTSINE, .5, 0, function()
			loadPage(p)
			flipcd = false
		end)
	end)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if not message_id == hash("escape") then
		gui.set_position(gui.get_node("info text"), vmath.vector3(960, 1140, 0))
	end
	if message_id == hash("unable") then
		gui.set_text(gui.get_node("info text"), "Not mature yet")
		gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1040, 0), gui.EASING_INSINE, .25, 0, function()
			timer.delay(.5, false, function()
				gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1140, 0), gui.EASING_INSINE, .25, 0)
			end)
		end)
	elseif message_id == hash("pollinate") then
		gui.set_text(gui.get_node("info text"), "Pick another flower!")
		gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1040, 0), gui.EASING_INSINE, .25, 0)
	elseif message_id == hash("escape") then
		gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1140, 0), gui.EASING_INSINE, .25, 0)
	elseif message_id == hash("harvest") then
		gui.set_text(gui.get_node("info text"), "Harvested " .. flowerInfo.ID(message[1])[1] .. "!")
		gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1040, 0), gui.EASING_INSINE, .25, 0, function()
			timer.delay(.5, false, function()
				gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1140, 0), gui.EASING_INSINE, .25, 0)
			end)
		end)
	end
end


function on_input(self, action_id, action)

	local selectionTable = {gui.get_node("herbs"), gui.get_node("settings")}
	
	local base = gui.get_node("base")
	for i, v in ipairs(selectionTable) do
		if gui.pick_node(v, action.x, action.y) and screenSelection ~= i then
			if action_id == hash("touch") and action.pressed then
				print(i)
				screenSelection = i
				gui.animate(v, gui.PROP_POSITION, vmath.vector3(-124, gui.get_position(v).y, 0), gui.EASING_INSINE, .1, 0)
			else
				gui.animate(v, gui.PROP_POSITION, vmath.vector3(-115, gui.get_position(v).y, 0), gui.EASING_INSINE, .1, 0)
			end
		elseif screenSelection ~= i then
			gui.animate(v, gui.PROP_POSITION, vmath.vector3(-110, gui.get_position(v).y, 0), gui.EASING_INSINE, .1, 0)
		end
		
	end
	if gui.pick_node(gui.get_node("herbbutton"), action.x, action.y) and action_id == hash("touch") and action.pressed then
		if inScreen == nil then
		
		elseif inScreen then
			inScreen = nil
			mouseCheck.escapeGui()
			gui.animate(gui.get_node("bookmarks"), gui.PROP_POSITION, vmath.vector3(4, 0, 0), gui.EASING_INSINE, .5, 0)
			gui.animate(base, gui.PROP_POSITION, vmath.vector3(2600, 540, 0), gui.EASING_INOUTSINE, 1, 0, function()
				inScreen = false
			end)
		else
			gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1140, 0), gui.EASING_INSINE, .25, 0)
			loadPage(page)
			inScreen = nil
			gui.animate(base, gui.PROP_POSITION, vmath.vector3(960, 540, 0), gui.EASING_INOUTSINE, 1, 0, function()
				inScreen = true
				gui.animate(gui.get_node("bookmarks"), gui.PROP_POSITION, vmath.vector3(0, 0, 0), gui.EASING_INSINE, .5, 0)
			end)
			mouseCheck.changeState(2)
		end
	end
	if inScreen then
		local useButton = gui.get_node("useButton")
		local leftArrow = gui.get_node("leftArrow")
		local rightArrow = gui.get_node("rightArrow")
		if selected == page then
			gui.play_flipbook(useButton, "clicked")
		elseif gui.pick_node(useButton, action.x, action.y) then
			if (action_id == hash("touch") and action.pressed) and selected ~= page then
				gui.play_flipbook(useButton, "clicked")
				selected = page
				msg.post("/flower_factory#flowery", "flowerselect", {uwu = selected})
			else
				gui.play_flipbook(useButton, "selected")
			end
		else
			gui.play_flipbook(useButton, "initial")
		end
		if page == 1 then
			gui.play_flipbook(leftArrow, "clicked")
		elseif gui.pick_node(leftArrow, action.x, action.y) then
			if (action_id == hash("touch") and action.pressed) and not flipcd then
				gui.play_flipbook(leftArrow, "clicked")
				page = page - 1
				flipcd = true
				left(page)
			else
				gui.play_flipbook(leftArrow, "selected")
			end
		else
			gui.play_flipbook(leftArrow, "initial")
		end
		if gui.pick_node(rightArrow, action.x, action.y) then
			if (action_id == hash("touch") and action.pressed) and not flipcd then
				gui.play_flipbook(rightArrow, "clicked")
				page = page + 1
				flipcd = true
				right(page)
			else
				gui.play_flipbook(rightArrow, "selected")
			end
		else
			gui.play_flipbook(rightArrow, "initial")
		end
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
