go.property("cycle", 0)
go.property("item_id", msg.url())
go.property("flower_id", 0)
local deletion = false

local mouseCheck = require("scripts.mouseCheck")

function init(self)
	go.animate(".", "scale", go.PLAYBACK_ONCE_FORWARD, 1, go.EASING_INOUTELASTIC, .5)
	mouseCheck.changeState(1.1)
	timer.delay(.5, false, function()
		msg.post(".", "acquire_input_focus")
	end)
end

function final(self)
	
end

function update(self, dt)
	if not deletion then
		mouseCheck.changeState(1.1)
	end
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	self.cycle = message[1]
end

function on_input(self, action_id, action)
	local mouse_pos = mouseCheck.getPos()
	if mouse_pos.x <= go.get_position().x + 180 and mouse_pos.x >= go.get_position().x + 30 and mouse_pos.y <= go.get_position().y + 70.5 and mouse_pos.y >= go.get_position().y + 45.5 then
		if action_id == hash("touch") and action.pressed then
			if self.cycle == 3 then
				msg.post("/book#Herbbook", "pollinate", {self.flower_id})
				mouseCheck.changeState(1.5)
				mouseCheck.store(self.flower_id, self.item_id)
				go.animate(".", "scale", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_INOUTELASTIC, .5)
				msg.post(".", "release_input_focus")
				msg.post(self.item_id, "delete", {1})
				timer.delay(.5, false, function()
					go.delete()
				end)
			else
				msg.post("/book#Herbbook", "unable", {1})
				go.animate(".", "scale", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_INOUTELASTIC, .5)
				msg.post(".", "release_input_focus")
				deletion = true
				msg.post(self.item_id, "delete", {1})
				timer.delay(.5, false, function()
					mouseCheck.escapeGui()
					go.delete()
				end)
			end
		end
	elseif mouse_pos.x <= go.get_position().x + 132.5 and mouse_pos.x >= go.get_position().x + 30 and mouse_pos.y <= go.get_position().y + 35 and mouse_pos.y >= go.get_position().y + 10 then
		if action_id == hash("touch") and action.pressed then
			if self.cycle == 3 then
				msg.post("/book#Herbbook", "harvest", {self.flower_id})
				msg.post(self.item_id, "harvested", {1})
			else
				msg.post("/book#Herbbook", "unable", {1})
			end
			go.animate(".", "scale", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_INOUTELASTIC, .5)
			msg.post(".", "release_input_focus")
			deletion = true
			msg.post(self.item_id, "delete", {1})
			timer.delay(.5, false, function()
				mouseCheck.escapeGui()
				go.delete()
			end)
		end
	elseif action_id == hash("touch") and action.pressed then
		go.animate(".", "scale", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_INOUTELASTIC, .5)
		msg.post(".", "release_input_focus")
		deletion = true
		mouseCheck.escapeGui()
		msg.post(self.item_id, "delete", {1})
		timer.delay(.5, false, function()
			go.delete()
		end)
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
