go.property("seed_time", 0)
go.property("cycle", 0)
go.property("id", 0)
go.property("item_id", 0)
go.property("selection", msg.url())
go.property("selected", false)
go.property("circle", msg.url())
local mouseCheck = require("scripts.mouseCheck")
local flowerInfo = require("scripts.flowerInfo")

local mouse_pos
local cd = false

function init(self)
	self.item_id = go.get_id()
	go.set("#sprite", "cursor", (4 * (self.id - 1)) / 8192)
	self.circle = factory.create("#circlefactory", go.get_position("."), nil, {seed_time = self.seed_time}, 1)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	mouse_pos = mouseCheck.getPos()
	local growth = os.time() - self.seed_time
	if (growth >= 3600) then 
		go.set("#sprite", "cursor", (4 * (self.id - 1) + 3) / 8192)
		self.cycle = 3
	elseif (growth >= 2400) then
		go.set("#sprite", "cursor", (4 * (self.id - 1) + 2) / 8192)
		self.cycle = 2
	elseif (growth >= 1200) then
		go.set("#sprite", "cursor", (4 * (self.id - 1) + 1) / 8192)
		self.cycle = 1
	else
		go.set("#sprite", "cursor", (4 * (self.id - 1)) / 8192)
		self.cycle = 0
	end
	if self.selection ~= nil then
		msg.post(self.selection, "cycle", {self.cycle})
	end
	if math.abs(mouse_pos.x - go.get_position(self.item_id).x) <= 30 and math.abs(mouse_pos.y - go.get_position(self.item_id).y + 20) <= 40 then
		mouseCheck.changeState(1)
		go.animate(self.circle, "position.y", go.PLAYBACK_ONCE_FORWARD, go.get_position(".").y + 60, go.EASING_INOUTELASTIC, .05)
	else
		go.animate(self.circle, "position.y", go.PLAYBACK_ONCE_FORWARD, go.get_position(".").y, go.EASING_INOUTELASTIC, .05)
	end
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end


function on_message(self, message_id, message, sender)
	if message_id == hash("selected") then
		if self.selected then
			if self.cycle == 3 then
				msg.post("/book#Herbbook", "harvest", {self.id})
				go.delete(self.circle)
				go.delete()
			else
				msg.post("/book#Herbbook", "unable", {1})
			end
		else
			self.selected = true
			go.animate(".", "euler.z", go.PLAYBACK_ONCE_FORWARD, 5, go.EASING_LINEAR, 0.25, 0, function()
				go.animate(".", "euler.z", go.PLAYBACK_ONCE_FORWARD, -5, go.EASING_LINEAR, 0.5, 0, function()
					go.animate(".", "euler.z", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_LINEAR, 0.25)
				end)
			end)
			timer.delay(1, false, function()
				self.selected = false
			end)
		end
	elseif message_id == hash("delete") then
		self.selection = nil
	elseif message_id == hash("harvested") then
		go.delete(self.circle)
		go.delete()
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end