local flowerInfo = require("scripts.flowerInfo")
local mouseCheck = require("scripts.mouseCheck")
local flfact = "#flfact"
local flowers = {}

local flower_id = 1
--ID table -> 1. Name 2. Species 3. Description 4. Unlocked

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("/camera#camera", "acquire_camera_focus")
	local tempGarden = flowerInfo.sendGarden()
	for i, t in ipairs(tempGarden) do
		local f = factory.create(flfact, t[2], nil, {id = t[1], seed_time = t[3]}, 1)
		table.insert(flowers, f)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("flowerselect") then
		flower_id = message.uwu
	elseif message_id == hash("flower create") then
		local temp = flowerInfo.sendGarden()
	elseif message_id == hash("spawn") then
		local f = factory.create(flfact, vmath.vector3(message[1], message[2], .5 - message[2] / 1000), nil, { id = message[3] }, 1)
		table.insert(flowers, f)
		flowerInfo.insertGarden({flower_id, mouse_pos, f})
	end
end

function on_input(self, action_id, action)
	local mouse_pos = camera.screen_to_world(vmath.vector3(action.screen_x, action.screen_y, 0), "/camera#camera")

	if action_id == hash("touch") and action.pressed and (mouseCheck.getState() == 1 or mouseCheck.getState() == 1.5) then
		for i, item_id in ipairs(flowers) do
			if not go.exists(item_id) then
				table.remove(flowers, i)
				flowerInfo.removeGarden(i)
			elseif math.abs(mouse_pos.x - go.get_position(item_id).x) <= 30 and math.abs(mouse_pos.y - go.get_position(item_id).y + 20) <= 40 and mouseCheck.getState() ~= 1.1 then
				msg.post(item_id, "selected", {"uwu"})
			end
		end
	end
	
	if action_id == hash("righty") and action.pressed and mouse_pos.x > 340 and mouse_pos.x < 1580 and mouse_pos.y > 70 and mouse_pos.y < 1000 and mouseCheck.getState() == 0 then
		local f = factory.create(flfact, vmath.vector3(mouse_pos.x, mouse_pos.y, .5 - mouse_pos.y / 1000), nil, { id = flower_id , seed_time = os.time()}, 1)
		table.insert(flowers, f)
		flowerInfo.insertGarden({flower_id, mouse_pos, os.time()})
	end
end