local flowerInfo = require("scripts.flowerInfo")
local mouseCheck = require("scripts.mouseCheck")
local seasons = require("scripts.seasons")
local scene = require("scripts.scene")

function init(self)
	local seed = os.time()
	math.randomseed(seed)

	go.set("#rainshade", "tint.w", 0)
	go.set("#snowshade", "tint.w", 0)
	go.set("#rainshade", "scale", vmath.vector3(200, 200, 0))
	go.set("#snowshade", "scale", vmath.vector3(200, 200, 0))
end

local changetime = os.time()

local width = 1920
local height = 1080

function update(self, dt)
	if scene.get() == 1 then
		dt = os.time() - changetime
		changetime = os.time()
		if dt > 0 then
			seasons.addTime(dt)
		end
		mouseCheck.reset()
		local weather = seasons.getWeather()
		if weather >= 4 and weather <= 6 then
			go.set("#rainshade", "cursor", 168/224)
			go.set("#rainshade", "tint.w", (weather - 2) / 10)
			if weather == 4 then
				for i = 0, math.random(0, 1), 1 do
					factory.create("#rainfact", vmath.vector3(math.random(width), math.random(height), .8), nil, nil, 3)
				end
			elseif weather == 5 then
				for i = 0, math.random(2, 3), 1 do
					factory.create("#rainfact", vmath.vector3(math.random(width), math.random(height), .8), nil, nil, 3)
				end
			else
				for i = 0, math.random(5, 6), 1 do
					factory.create("#rainfact", vmath.vector3(math.random(width), math.random(height), .8), nil, nil, 3)
				end
			end
		else
			go.set("#rainshade", "tint.w", 0)
		end
		if weather >= 7 and weather <= 9 then
			go.set("#snowshade", "tint.w", (weather - 5) / 10)
			if math.random(0, 1) == 0 then
				if weather == 7 then
					for i = 0, math.random(0, 1), 1 do
						factory.create("#snowfact", vmath.vector3(math.random(width), math.random(height), .8), nil, nil, 3)
					end
				elseif weather == 8 then
					for i = 0, math.random(1, 2), 1 do
						factory.create("#snowfact", vmath.vector3(math.random(width), math.random(height), .8), nil, nil, 3)
					end
				else
					for i = 0, math.random(3, 4), 1 do
						factory.create("#snowfact", vmath.vector3(math.random(width), math.random(height), .8), nil, nil, 3)
					end
				end
			end
		else
			go.set("#snowshade", "tint.w", 0)
		end
		if seasons.getSeason() == 4 then
			go.set("#background", "cursor", 1/2)
		else
			go.set("#background", "cursor", 0/2)
		end
	end
end