--local WIDTH = tonumber(sys.get_config("display.width")) 
--local HEIGHT = tonumber(sys.get_config("display.height")) 
local mouseCheck = require("scripts.mouseCheck")
local clickCD = false
local width = 1920
local height = 1080

function init(self)
	msg.post(".", "acquire_input_focus")
	gui.set_render_order(1)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	
end

function on_input(self, action_id, action)
	local box = gui.get_node("box")
	
	local mouse_pos = camera.screen_to_world(vmath.vector3(action.screen_x, action.screen_y, 0), "/camera#camera")

	mouseCheck.changePos(mouse_pos)
	local screen = vmath.vector3(mouse_pos.x + 20, mouse_pos.y - 19.5, 0)
	gui.set_position(box, screen)
	if mouseCheck.getState() == 2 or mouseCheck.getState() == 1.1 then
		if action_id == hash("touch") and action.pressed then
			gui.play_flipbook(box, "4")			
			clickCD = true
			timer.delay(.15, false, function()
				gui.play_flipbook(box, "3")
				clickCD = false
			end)
		elseif clickCD == false then
			gui.play_flipbook(box, "3")
		end
	elseif mouseCheck.getState() == 1.5 then
		gui.play_flipbook(box, "6")
		if action_id == hash("touch") and action.pressed then
			gui.play_flipbook(box, "7")			
			clickCD = true
			timer.delay(.15, false, function()
				gui.play_flipbook(box, "6")
				clickCD = false
			end)
		end
	elseif mouse_pos.x > 340 and mouse_pos.x < 1580 and mouse_pos.y > 70 and mouse_pos.y < 1000 then
		if action_id == hash("righty") and action.pressed then
			gui.play_flipbook(box, "1")
			clickCD = true
			timer.delay(.15, false, function()
				gui.play_flipbook(box, "0")
				clickCD = false
			end)
		elseif clickCD == false then
			gui.play_flipbook(box, "0")
		end
	else
		gui.play_flipbook(box, "3")
	end

	-- enable/disable mouse cursor depending on if we're inside or outside the game window
	if screen.x < 0 or screen.y < 0 or screen.x > width or screen.y > height then
		defos.set_cursor_visible(true)
		gui.set_visible(box, false)
	else
		defos.set_cursor_visible(false)
		gui.set_visible(box, true)
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
