local flowerInfo = require("scripts.flowerInfo")
local mouseCheck = require("scripts.mouseCheck")
local seasons = require("scripts.seasons")
local inScreen = false
local inSeed = false
local screenSelection = 1
local selected = 1
local page = 1
local flipcd = false
local inflip = false
local insort = false
local upAmount = 1
local dwAmount = 1

local alamancStorage = {}
local alamancTable = {}
local alamancTable1 = {}
local temptemptempTable = {}
local alamancPage = 1

local seedStorage = {}
local seedTable = {}
local seedPage = 1

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("/flower_factory#flowery", "flowerselect", {uwu = 1})
	alamancTable = {gui.get_node("slot1"), gui.get_node("slot2"), gui.get_node("slot3"), gui.get_node("slot4"), gui.get_node("slot5"), gui.get_node("slot6"), gui.get_node("slot7"), gui.get_node("slot8"), gui.get_node("slot9")}
	alamancTable1 = {gui.get_node("slot"), gui.get_node("slot10"), gui.get_node("slot11"), gui.get_node("slot12"), gui.get_node("slot13"), gui.get_node("slot14"), gui.get_node("slot15"), gui.get_node("slot16"), gui.get_node("slot17")}
	seedTable = {gui.get_node("seedslot1"), gui.get_node("seedslot2"), gui.get_node("seedslot3"), gui.get_node("seedslot4"), gui.get_node("seedslot5"), gui.get_node("seedslot6"), gui.get_node("seedslot7"), gui.get_node("seedslot8"), gui.get_node("seedslot9")}
end

local function uploadSeeds()
	local tempstart = (seedPage - 1) * 9 + 1
	for i = 0, 8, 1 do
		local ref = seedTable[i + 1]
		if seedStorage[tempstart + i] then
			gui.set_visible(ref, true)
			gui.play_flipbook(ref, "1", nil, {playback_rate = 0})
			gui.set_flipbook_cursor(ref, (4 * seedStorage[tempstart + i][4] - 1) / 127)
		else
			gui.set_visible(ref, false)
		end
	end
end

local function downloadSeeds()
	local ceaser = seasons.getSeason()
	local weathertemp = nil
	if seasons.getWeather() >= 4 and seasons.getWeather() <= 9 then
		weathertemp = 5
	end
	seedStorage = flowerInfo.getAllSeasonWeather(ceaser, weathertemp)
	seedPage = 1
	uploadSeeds()
end

local function checkCollision(table, action)
	for i, v in ipairs(table) do
		if gui.pick_node(v, action.x, action.y) then
			return true
		end
	end
	return false
end

local function updateAlamanc()
	alamancStorage = flowerInfo.unlockTable()
end

local function navigateAlamanc(thing)
	if thing == 1 then
		alamancPage = alamancPage + 1
	elseif thing == 0 then
		alamancPage = alamancPage - 1
	end
	for i, p in ipairs(alamancStorage) do
		if i <= 3 * (alamancPage - 1) then
			
		elseif i > 3 * (alamancPage + 2) then
			break
		else
			local temp = i - 3 * (alamancPage - 1)
			gui.set_visible(alamancTable[temp], true)
			gui.play_flipbook(alamancTable[temp], "1", nil, {playback_rate = 0})
			gui.set_flipbook_cursor(alamancTable[temp], (4 * p - 1) / 127)
		end
	end
end

local function loadLeftPage1(p, c)
	
	gui.set_enabled(gui.get_node("alamanc1"), false)
	if c == 1 then
		gui.set_visible(gui.get_node("flowerbg"), false)
		if p > 0 then
			local flower = flowerInfo.ID(p)
			if flower[2] == 2 then
				gui.set_visible(gui.get_node("photo1"), true)
				gui.set_visible(gui.get_node("photo2"), true)
				gui.set_visible(gui.get_node("flower"), true)
				gui.play_flipbook(gui.get_node("flower"), "1", nil, {playback_rate = 0})
				gui.set_flipbook_cursor(gui.get_node("flower"), (4 * flower[1][4] - 1) / 127)
			else
				gui.set_visible(gui.get_node("photo1"), false)
				gui.set_visible(gui.get_node("photo2"), false)
				gui.set_visible(gui.get_node("flower"), false)
			end
		elseif p == 0 then
			gui.set_visible(gui.get_node("photo1"), false)
			gui.set_visible(gui.get_node("photo2"), false)
			gui.set_visible(gui.get_node("flower"), false)
			gui.set_visible(gui.get_node("flowerbg"), false)
			gui.set_enabled(gui.get_node("alamanc1"), true)
			for i, p in ipairs(alamancTable) do
				gui.set_visible(p, false)
			end
			for i, p in ipairs(alamancStorage) do
				if i >= 10 then
					break
				else
					gui.set_visible(alamancTable[i], true)
					gui.play_flipbook(alamancTable[i], "1", nil, {playback_rate = 0})
					gui.set_flipbook_cursor(alamancTable[i], (4 * p - 1) / 127)
					alamancPage = 1
				end
			end
		end
	elseif c == 2 then
		gui.set_visible(gui.get_node("photo1"), true)
		gui.set_visible(gui.get_node("photo2"), true)
		gui.set_visible(gui.get_node("flower"), false)
		gui.set_visible(gui.get_node("flowerbg"), true)
	end
end

local function loadLeftPage2(p, c)
	gui.set_enabled(gui.get_node("alamanc"), false)
	if c == 1 then
		gui.set_visible(gui.get_node("flowerbg1"), false)
		if p > 0 then
			local flower = flowerInfo.ID(p)
			if flower[2] == 2 then
				gui.set_visible(gui.get_node("photo3"), true)
				gui.set_visible(gui.get_node("photo4"), true)
				gui.set_visible(gui.get_node("flower1"), true)
				gui.play_flipbook(gui.get_node("flower1"), "1", nil, {playback_rate = 0})
				gui.set_flipbook_cursor(gui.get_node("flower1"), (4 * flower[1][4] - 1) / 127)
			else
				gui.set_visible(gui.get_node("photo3"), false)
				gui.set_visible(gui.get_node("photo4"), false)
				gui.set_visible(gui.get_node("flower1"), false)
			end
		elseif p == 0 then
			gui.set_visible(gui.get_node("photo3"), false)
			gui.set_visible(gui.get_node("photo4"), false)
			gui.set_visible(gui.get_node("flower1"), false)
			gui.set_visible(gui.get_node("flowerbg"), false)
			gui.set_enabled(gui.get_node("alamanc"), true)
			for i, p in ipairs(alamancTable1) do
				gui.set_visible(p, false)
			end
			for i, p in ipairs(alamancStorage) do
				if i >= 10 then
					break
				else
					gui.set_visible(alamancTable1[i], true)
					gui.play_flipbook(alamancTable1[i], "1", nil, {playback_rate = 0})
					gui.set_flipbook_cursor(alamancTable1[i], (4 * p - 1) / 127)
				end
			end
		end
	elseif c == 2 then
		gui.set_visible(gui.get_node("photo3"), true)
		gui.set_visible(gui.get_node("photo4"), true)
		gui.set_visible(gui.get_node("flower1"), false)
		gui.set_visible(gui.get_node("flowerbg1"), true)
	end
end

local function loadRightPage1(p, c)
	if p == nil then
		
	elseif c == 1.5 or p == 0 and not (c >= 2) then
		if p == 0 then
			p = 1
		end
		gui.set_visible(gui.get_node("settings stuff"), false)
		gui.set_visible(gui.get_node("fullscreen"), false)
		gui.set_visible(gui.get_node("mute"), false)
		gui.set_visible(gui.get_node("quitButton"), false)
		gui.set_visible(gui.get_node("titleText"), true)
		gui.set_visible(gui.get_node("subtitleText"), true)
		gui.set_visible(gui.get_node("description"), true)
		if p > 0 then
			local flower = flowerInfo.ID(p)
			gui.set_line_break(gui.get_node("description"), true)
			if flower[2] == 2 then
				gui.set_text(gui.get_node("titleText"), flower[1][1])
				gui.set_text(gui.get_node("subtitleText"), flower[1][2])
				gui.set_text(gui.get_node("description"), flower[1][3][1] .. "\n\n" .. flower[1][3][2])
			elseif flower[2] == 1 then
				gui.set_text(gui.get_node("titleText"), flower[1][1])
				gui.set_text(gui.get_node("subtitleText"), flower[1][2])
				gui.set_text(gui.get_node("description"), flower[1][3][1])

			else
				gui.set_text(gui.get_node("titleText"), "Undiscovered")
				gui.set_text(gui.get_node("subtitleText"), "?????")
				gui.set_text(gui.get_node("description"), flower[1][3][1])
			end
		end
	elseif c == 1 then
		gui.set_visible(gui.get_node("settings stuff"), false)
		gui.set_visible(gui.get_node("fullscreen"), false)
		gui.set_visible(gui.get_node("mute"), false)
		gui.set_visible(gui.get_node("titleText"), true)
		gui.set_visible(gui.get_node("subtitleText"), true)
		gui.set_visible(gui.get_node("description"), true)
		if p > 0 then
			local flower = flowerInfo.ID(p)
			gui.set_line_break(gui.get_node("description"), true)
			if flower[2] == 2 then
				gui.set_text(gui.get_node("titleText"), flower[1][1])
				gui.set_text(gui.get_node("subtitleText"), flower[1][2])
				gui.set_text(gui.get_node("description"), flower[1][3][1] .. "\n\n" .. flower[1][3][2])
			elseif flower[2] == 1 then
				gui.set_text(gui.get_node("titleText"), flower[1][1])
				gui.set_text(gui.get_node("subtitleText"), flower[1][2])
				gui.set_text(gui.get_node("description"), flower[1][3][1])

			else
				gui.set_text(gui.get_node("titleText"), "Undiscovered")
				gui.set_text(gui.get_node("subtitleText"), "?????")
				gui.set_text(gui.get_node("description"), flower[1][3][1])
			end
		end
	elseif c == 2 then
		gui.set_visible(gui.get_node("settings stuff"), true)
		gui.set_visible(gui.get_node("fullscreen"), true)
		gui.set_visible(gui.get_node("mute"), true)
		gui.set_visible(gui.get_node("quitButton"), true)
		gui.set_visible(gui.get_node("titleText"), false)
		gui.set_visible(gui.get_node("subtitleText"), false)
		gui.set_visible(gui.get_node("description"), false)
	end
end

local function loadRightPage2(p, c)
	if c == 1.5 or p == 0 and not (c >= 2) then
		if p == 0 then
			p = 1
		end
		gui.set_visible(gui.get_node("settings stuff1"), false)
		gui.set_visible(gui.get_node("fullscreen1"), false)
		gui.set_visible(gui.get_node("mute1"), false)
		gui.set_visible(gui.get_node("quitButton1"), false)
		gui.set_visible(gui.get_node("titleText1"), true)
		gui.set_visible(gui.get_node("subtitleText1"), true)
		gui.set_visible(gui.get_node("description1"), true)
		if p > 0 then
			local flower = flowerInfo.ID(p)
			gui.set_line_break(gui.get_node("description1"), true)
			if flower[2] == 2 then
				gui.set_text(gui.get_node("titleText1"), flower[1][1])
				gui.set_text(gui.get_node("subtitleText1"), flower[1][2])
				gui.set_text(gui.get_node("description1"), flower[1][3][1] .. "\n\n" .. flower[1][3][2])
			elseif flower[2] == 1 then
				gui.set_text(gui.get_node("titleText1"), flower[1][1])
				gui.set_text(gui.get_node("subtitleText1"), flower[1][2])
				gui.set_text(gui.get_node("description1"), flower[1][3][1])
			else
				gui.set_text(gui.get_node("titleText1"), "Undiscovered")
				gui.set_text(gui.get_node("subtitleText1"), "?????")
				gui.set_text(gui.get_node("description1"), flower[1][3][1])
			end
		end
	elseif c == 1 then
		gui.set_visible(gui.get_node("settings stuff1"), false)
		gui.set_visible(gui.get_node("fullscreen1"), false)
		gui.set_visible(gui.get_node("mute1"), false)
		gui.set_visible(gui.get_node("quitButton1"), false)
		gui.set_visible(gui.get_node("titleText1"), true)
		gui.set_visible(gui.get_node("subtitleText1"), true)
		gui.set_visible(gui.get_node("description1"), true)
		if p > 0 then
			local flower = flowerInfo.ID(p)
			gui.set_line_break(gui.get_node("description1"), true)
			if flower[2] == 2 then
				gui.set_text(gui.get_node("titleText1"), flower[1][1])
				gui.set_text(gui.get_node("subtitleText1"), flower[1][2])
				gui.set_text(gui.get_node("description1"), flower[1][3][1] .. "\n\n" .. flower[1][3][2])
			elseif flower[2] == 1 then
				gui.set_text(gui.get_node("titleText1"), flower[1][1])
				gui.set_text(gui.get_node("subtitleText1"), flower[1][2])
				gui.set_text(gui.get_node("description1"), flower[1][3][1])
			else
				gui.set_text(gui.get_node("titleText1"), "Undiscovered")
				gui.set_text(gui.get_node("subtitleText1"), "?????")
				gui.set_text(gui.get_node("description1"), flower[1][3][1])
			end
		end
	elseif c == 2 then
		gui.set_visible(gui.get_node("titleText1"), false)
		gui.set_visible(gui.get_node("subtitleText1"), false)
		gui.set_visible(gui.get_node("description1"), false)
		gui.set_visible(gui.get_node("settings stuff1"), true)
		gui.set_visible(gui.get_node("fullscreen1"), true)
		gui.set_visible(gui.get_node("mute1"), true)
		gui.set_visible(gui.get_node("quitButton1"), true)
	end	
end

local function loadPage(p, c)
	gui.set_scale(gui.get_node("page1"), vmath.vector3(2/30, 2/30, 1))
	gui.set_position(gui.get_node("page1"), vmath.vector3(-8.5, 0, 0))
	gui.set_scale(gui.get_node("page2"), vmath.vector3(2/30, 2/30, 1))
	gui.set_position(gui.get_node("page2"), vmath.vector3(8.5, 0, 0))
	loadLeftPage1(p, c)
	loadRightPage1(p, c)
	screenSelection = c
end

local function left(p, c)
	loadRightPage2(page, screenSelection)
	page = p
	screenSelection = c
	
	loadLeftPage2(p, c)
	
	gui.set_scale(gui.get_node("page2"), vmath.vector3(0, 2/30, 1))
	gui.set_position(gui.get_node("page2"), vmath.vector3(0, 0, 0))

	loadRightPage1(p, c)

	gui.animate(gui.get_node("page1"), gui.PROP_SCALE, vmath.vector3(0, 2/30, 1), gui.EASING_INSINE, .5, 0, function()
		gui.animate(gui.get_node("page2"), gui.PROP_SCALE, vmath.vector3(2/30, 2/30, 1), gui.EASING_OUTSINE, .5, 0)
	end)
	gui.animate(gui.get_node("page1"), gui.PROP_POSITION, vmath.vector3(0, 0, 0), gui.EASING_INSINE, .5, 0, function()
		gui.animate(gui.get_node("page2"), gui.PROP_POSITION, vmath.vector3(8.5, 0, 0), gui.EASING_OUTSINE, .5, 0, function()
			loadPage(p, c)
			flipcd = false
		end)
	end)
end

local function right(p, c)

	loadLeftPage2(page, screenSelection)
	page = p
	screenSelection = c

	loadRightPage2(p, c)

	gui.set_scale(gui.get_node("page1"), vmath.vector3(0, 2/30, 1))
	gui.set_position(gui.get_node("page1"), vmath.vector3(0, 0, 0))

	loadLeftPage1(p, c)

	gui.animate(gui.get_node("page2"), gui.PROP_SCALE, vmath.vector3(0, 2/30, 1), gui.EASING_INSINE, .5, 0, function()
		gui.animate(gui.get_node("page1"), gui.PROP_SCALE, vmath.vector3(2/30, 2/30, 1), gui.EASING_OUTSINE, .5, 0)
	end)
	gui.animate(gui.get_node("page2"), gui.PROP_POSITION, vmath.vector3(0, 0, 0), gui.EASING_INSINE, .5, 0, function()
		gui.animate(gui.get_node("page1"), gui.PROP_POSITION, vmath.vector3(-8.5, 0, 0), gui.EASING_OUTSINE, .5, 0, function()
			loadPage(p, c)
			flipcd = false
		end)
	end)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

--y values:
--weather 1 = 970 weather 2 = 909 weather 3 = 843
local patternTime = 3600
--61 pixel diff

function update(self, dt)
	local time, pattern = seasons.getTime()
	gui.set(gui.get_node("needle"), gui.PROP_POSITION, vmath.vector3(-20, 970 - (61 * (pattern - 1 + (time / patternTime))), 0))

	local season = seasons.getSeason()
	if season == 1 then
		gui.play_flipbook(gui.get_node("season"), "spring", nil)
	elseif season == 2 then
		gui.play_flipbook(gui.get_node("season"), "summer", nil)
	elseif season == 3 then
		gui.play_flipbook(gui.get_node("season"), "autumn", nil)
	else
		gui.play_flipbook(gui.get_node("season"), "winter", nil)
	end
end

function on_message(self, message_id, message, sender)
	if not message_id == hash("escape") then
		gui.set_position(gui.get_node("info text"), vmath.vector3(960, 1140, 0))
	end
	if message_id == hash("unable") then
		gui.set_text(gui.get_node("info text"), "Not mature yet")
		gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1040, 0), gui.EASING_INSINE, .25, 0, function()
			timer.delay(.5, false, function()
				gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1140, 0), gui.EASING_INSINE, .25, 0)
			end)
		end)
	elseif message_id == hash("pollinate") then
		gui.set_text(gui.get_node("info text"), "Pick another flower!")
		gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1040, 0), gui.EASING_INSINE, .25, 0)
	elseif message_id == hash("escape") then
		gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1140, 0), gui.EASING_INSINE, .25, 0)
	elseif message_id == hash("harvest") then
		gui.set_text(gui.get_node("info text"), "Harvested " .. flowerInfo.ID(message[1])[1][1] .. "!")
		gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1040, 0), gui.EASING_INSINE, .25, 0, function()
			timer.delay(.5, false, function()
				gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1140, 0), gui.EASING_INSINE, .25, 0)
			end)
		end)
	end
end

function on_input(self, action_id, action)
	--local x, y, w, h = defos.get_window_size()
	--local ratio = 1920 / w
	local selectionTable = {gui.get_node("herbs"), gui.get_node("settings")}

	-- Bookmarks
	if screenSelection == 2 then
		local settingsTable = {"fullscreen", "mute"}
		for i, v in ipairs(settingsTable) do
			if gui.pick_node(gui.get_node(v), action.x, action.y) and action.pressed and action_id == hash("touch") then
				if gui.get_flipbook(gui.get_node(v)) == hash("unchecked") then
					gui.play_flipbook(gui.get_node(v), "checked", nil, {playback_rate = 0})
					gui.play_flipbook(gui.get_node(v .. 1), "checked", nil, {playback_rate = 0})
				else
					gui.play_flipbook(gui.get_node(v), "unchecked", nil, {playback_rate = 0})
					gui.play_flipbook(gui.get_node(v .. 1), "unchecked", nil, {playback_rate = 0})
				end
				if i == 1 then
					defos.toggle_fullscreen()
				else
					
				end
			end
		end	
		if gui.pick_node(gui.get_node("quitButton"), action.x, action.y) then
			gui.play_flipbook(gui.get_node("quitButton"), "hover", nil, {})
			if action.pressed and action_id == hash("touch") then
				flowerInfo.save()
				msg.post("@system:", "exit", {code = 0})
			end
		else
			gui.play_flipbook(gui.get_node("quitButton"), "initial", nil, {})
		end
	end

	-- Bookmark Traversal
	local base = gui.get_node("base")
	for i, v in ipairs(selectionTable) do
		if gui.pick_node(v, action.x, action.y) and screenSelection ~= i and not gui.pick_node(gui.get_node("page3"), action.x, action.y) then
			if action_id == hash("touch") and action.pressed then
				if i > screenSelection then
					right(0, i)
				else
					left(0, i)
				end
				page = 0
				screenSelection = i
				gui.animate(v, gui.PROP_POSITION, vmath.vector3(-124, gui.get_position(v).y, 0), gui.EASING_INSINE, .1, 0)
			else
				gui.animate(v, gui.PROP_POSITION, vmath.vector3(-115, gui.get_position(v).y, 0), gui.EASING_INSINE, .1, 0)
			end
		elseif screenSelection ~= i then
			gui.animate(v, gui.PROP_POSITION, vmath.vector3(-110, gui.get_position(v).y, 0), gui.EASING_INSINE, .1, 0)
		end
	end

	if inSeed or inScreen then
		if not (gui.pick_node(gui.get_node("seedbase"), action.x, action.y) or gui.pick_node(gui.get_node("base"), action.x, action.y)) and action.pressed then
			inSeed = false
			gui.animate(gui.get_node("seedbase"), gui.PROP_POSITION, vmath.vector3(-450, 540, 0), gui.EASING_INOUTSINE, 1)
			inScreen = nil
			mouseCheck.escapeGui()
			gui.animate(gui.get_node("bookmarks"), gui.PROP_POSITION, vmath.vector3(4, 0, 0), gui.EASING_INSINE, .5, 0)
			gui.animate(base, gui.PROP_POSITION, vmath.vector3(2600, 540, 0), gui.EASING_INOUTSINE, 1, 0, function()
				inScreen = false
			end)
		end
	end
	
	-- Opening the book
	if gui.pick_node(gui.get_node("herbbutton"), action.x, action.y) and action_id == hash("touch") and action.pressed then
		if inScreen == nil then
		
		elseif inScreen then
			inScreen = nil
			mouseCheck.escapeGui()
			gui.animate(gui.get_node("bookmarks"), gui.PROP_POSITION, vmath.vector3(4, 0, 0), gui.EASING_INSINE, .5, 0)
			gui.animate(base, gui.PROP_POSITION, vmath.vector3(2600, 540, 0), gui.EASING_INOUTSINE, 1, 0, function()
				inScreen = false
			end)
		else
			gui.animate(gui.get_node("info text"), gui.PROP_POSITION, vmath.vector3(960, 1140, 0), gui.EASING_INSINE, .25, 0)
			loadPage(page, screenSelection)
			updateAlamanc()
			inScreen = nil
			gui.animate(base, gui.PROP_POSITION, vmath.vector3(960, 540, 0), gui.EASING_INOUTSINE, 1, 0, function()
				inScreen = true
				gui.animate(gui.get_node("bookmarks"), gui.PROP_POSITION, vmath.vector3(0, 0, 0), gui.EASING_INSINE, .5, 0)
			end)
			mouseCheck.changeState(2)
		end
		gui.animate(gui.get_node("seedbase"), gui.PROP_POSITION, vmath.vector3(-450, 540, 0), gui.EASING_INOUTSINE, 1)
		inSeed = false
	end
	
	-- Inside the book, outside the book and other book-related functions
	if inScreen then
		local leftArrow = gui.get_node("leftArrow")
		local rightArrow = gui.get_node("rightArrow")
		local checkBox = gui.get_node("sortBox")
		
		if gui.pick_node(checkBox, action.x, action.y) and action.pressed and (action_id == hash("touch")) then
			insort = not insort
			if insort then
				gui.play_flipbook(checkBox, "checked")
			else
				gui.play_flipbook(checkBox, "unchecked")
			end
		end
		if insort then
			upAmount, dwAmount = flowerInfo.findNextUnlock(page, 1), flowerInfo.findNextUnlock(page, 0)
		else
			upAmount, dwAmount = 1, 1
		end
		if page == 0 and screenSelection == 1 then
			for i, v in ipairs(alamancTable) do
				if gui.pick_node(v, action.x, action.y) then
					loadRightPage1(flowerInfo.pageNum(alamancStorage[i + 3 * (alamancPage - 1)]), 1.5)
				end
			end
			if alamancPage == 1 then
				gui.play_flipbook(gui.get_node("alamancUp1"), "clicked")
			else
				gui.play_flipbook(gui.get_node("alamancUp1"), "initial")
				if gui.pick_node(gui.get_node("alamancUp1"), action.x, action.y) and action_id == hash("touch") and action.pressed then
					navigateAlamanc(0)
				end
			end
			if #alamancStorage <= 3 * (alamancPage + 2)  then
				gui.play_flipbook(gui.get_node("alamancDown1"), "clicked")
			else
				gui.play_flipbook(gui.get_node("alamancDown1"), "initial")
				if gui.pick_node(gui.get_node("alamancDown1"), action.x, action.y) and action_id == hash("touch") and action.pressed then
					navigateAlamanc(1)
				end
			end
		elseif flipcd or screenSelection ~= 1 then
		
		end
		if page == 0 or screenSelection == 2 or dwAmount == 0 then
			gui.play_flipbook(leftArrow, "clicked")
		elseif gui.pick_node(leftArrow, action.x, action.y) then
			if (action_id == hash("touch") and action.pressed) and not flipcd then
				gui.play_flipbook(leftArrow, "clicked")
				flipcd = true
				left(page - dwAmount, screenSelection)
			else
				gui.play_flipbook(leftArrow, "selected")
			end
		else
			gui.play_flipbook(leftArrow, "initial")
		end
		if screenSelection == 2 or page == flowerInfo.getSize() - 1 or upAmount == 0 then
			gui.play_flipbook(rightArrow, "clicked")
		elseif gui.pick_node(rightArrow, action.x, action.y) then
			if (action_id == hash("touch") and action.pressed) and not flipcd then
				gui.play_flipbook(rightArrow, "clicked")
				flipcd = true
				right(page + upAmount, screenSelection)
			else
				gui.play_flipbook(rightArrow, "selected")
			end
		else
			gui.play_flipbook(rightArrow, "initial")
		end
	elseif inSeed then
		
	else
		gui.play_flipbook(gui.get_node("seedbag"), "initial")
		if checkCollision({gui.get_node("seedbag1"), gui.get_node("seedbag2"), gui.get_node("seedbag3")}, action) then
			if action.pressed and action_id == hash("touch") then
				inSeed = true
				gui.animate(gui.get_node("seedbase"), gui.PROP_POSITION, vmath.vector3(450, 540, 0), gui.EASING_INOUTSINE, 1)
				downloadSeeds()
			else
				gui.play_flipbook(gui.get_node("seedbag"), "hover")
			end
		end
	end

	
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
